language: go

install:
  - go get github.com/mattn/goveralls
  - go get gopkg.in/webnice/debug.v1
  - go get gopkg.in/webnice/log.v2

script:
  - make test
  - GOPATH=`pwd` $HOME/gopath/bin/goveralls -coverprofile=coverage.log -service=travis-ci -repotoken $COVERALLS_TOKEN

go:
  - 1.7
  - 1.8
  - 1.9
  - tip
